# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-04 12:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=254, null=True)),
                ('content', models.TextField(null=True)),
                ('datum', models.DateField(default=datetime.datetime(2017, 6, 4, 12, 17, 31, 827156))),
            ],
        ),
    ]
