# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-04 12:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='generalView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.BigIntegerField(null=True)),
                ('date', models.DateField(default=datetime.datetime(2017, 6, 4, 12, 17, 31, 829228))),
            ],
        ),
        migrations.CreateModel(
            name='userCreateReceipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.BigIntegerField(null=True)),
                ('date', models.DateField(default=datetime.datetime(2017, 6, 4, 12, 17, 31, 830334))),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userFormPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.BigIntegerField(null=True)),
                ('date', models.DateField(default=datetime.datetime(2017, 6, 4, 12, 17, 31, 829802))),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
