# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-04 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStatistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalview',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 4, 12, 22, 9, 326323)),
        ),
        migrations.AlterField(
            model_name='usercreatereceipe',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 4, 12, 22, 9, 327416)),
        ),
        migrations.AlterField(
            model_name='userformpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 4, 12, 22, 9, 326888)),
        ),
    ]
