# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-04 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumeintrag',
            name='datum',
            field=models.DateField(default=datetime.datetime(2017, 6, 4, 12, 22, 9, 323457)),
        ),
    ]
